# Generated by Django 2.1.2 on 2018-11-05 23:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='flex_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_plan', models.CharField(max_length=256)),
                ('current_flex', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='flex_transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=256)),
                ('transaction_type', models.CharField(max_length=256)),
                ('transaction_amount', models.FloatField()),
                ('balance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='product_info',
            fields=[
                ('barcode', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('price', models.FloatField()),
                ('location', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('access_key', models.CharField(max_length=10)),
                ('phone_number', models.BigIntegerField()),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('preferences', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='flex_transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flex_backend.User'),
        ),
        migrations.AddField(
            model_name='flex_info',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flex_backend.User'),
        ),
    ]
