# Generated by Django 2.1.1 on 2018-12-06 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex_backend', '0002_auto_20181119_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('price', models.FloatField()),
                ('location', models.CharField(max_length=256)),
                ('type', models.CharField(max_length=256)),
            ],
        ),
    ]
